### ISSUE TITLE
Github actions failed due to Node mismatch

### ISSUE THREAD

**Issue by MRK4863** [nateraw/huggingface-sync-action#3]
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by nateraw** [comment]
still haven't gotten to this. @MRK4863 I would love some help here if you have some time to look into it. No worries if not :)
